/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DonationContract } from "./DonationContract";
export type { DonationPlatform } from "./DonationPlatform";
